[project]
name = "srm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "h5py>=3.15.1",
    "matplotlib>=3.10.8",
    "numba>=0.63.1",
    "pandas>=2.3.3",
    "pandas-stubs~=2.3.3",
]
